#!/bin/bash
hash=$(echo "$1" | grep -oP "(?<=btih:)[a-fA-F0-9]*(?=&|$)")
if [ -z "$hash" ]
then
	exit -1
fi
aria2c --bt-metadata-only=true --bt-save-metadata=true -q --dir="$2" "$1"
upperhash=${hash^^}
if [ -a "$2/$upperhash.torrent" ]
then
	echo "$upperhash"
	exit 0
fi
lowerhash=${hash,,}
if [ -a "$2/$lowerhash.torrent" ]
then
	mv "$2/$lowerhash.torrent" "$2/$upperhash.torrent"
	echo "$upperhash"
	exit 0
fi
exit -1
