#!/bin/bash
SUFFIXES=('' 'K' 'M' 'G' 'T' 'P' 'E' 'Z' 'Y')
MULTIPLIER=1
shopt -s nocasematch

for SUFFIX in "${SUFFIXES[@]}"; do
	REGEX="^([0-9|\\.]+)\\s*(${SUFFIX}i?B?)$"

	if [[ $1 =~ $REGEX ]]; then
		value=${BASH_REMATCH[1]}
		bytes=$(echo "$value*$MULTIPLIER" | bc)
		echo "$bytes"
		exit 0
	fi

	((MULTIPLIER *= 1024))
done
exit 1
