#!/bin/bash
output=$(transmission-show "$1")
size_to_bytes_path=$(dirname "${BASH_SOURCE[0]}")/size-to-bytes
found_files=false
while read -r line
do
	if ${found_files}
	then
		file=$(echo "$line" | sed -n -r "s/^\s*(.*)\s+\([0-9]+(\.[0-9]+)?\s+\w+\)$/\1/p")
		size_unfiltered=$(echo "$line" | sed -n -r "s/^\s*(.*)\s+\(([0-9]+(\.[0-9]+)?\s+\w+)\)$/\2/p")
		if [ -n "$file" ]
		then
			size=$("$size_to_bytes_path" "$size_unfiltered")
			echo "$size - $file"
		fi
	else
		if [ "$line" == "FILES" ]
		then
			found_files=true
		fi
	fi
done <<< "$output"

